# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 1800, 760))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setRowCount(18)
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(107, 77, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(2, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(53, 96, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(4, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(8, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(10, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(12, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(14, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(15, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(239, 252, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(16, 15, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 14, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(219, 204, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(17, 15, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 800, 200, 100))
        self.pushButton.setObjectName("pushButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(1100, 800, 200, 100))
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Theory"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "START"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "08:00"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "09:00"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "10:00"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "11:00"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "12:00"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("MainWindow", "14:00"))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("MainWindow", "15:00"))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("MainWindow", "16:00"))
        item = self.tableWidget.item(0, 12)
        item.setText(_translate("MainWindow", "17:00"))
        item = self.tableWidget.item(0, 13)
        item.setText(_translate("MainWindow", "18:00"))
        item = self.tableWidget.item(0, 14)
        item.setText(_translate("MainWindow", "18:50"))
        item = self.tableWidget.item(0, 15)
        item.setText(_translate("MainWindow", "19:00"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "END"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "08:50"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "09:50"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "10:50"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("MainWindow", "11:50"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("MainWindow", "12:50"))
        item = self.tableWidget.item(1, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(1, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(1, 9)
        item.setText(_translate("MainWindow", "14:50"))
        item = self.tableWidget.item(1, 10)
        item.setText(_translate("MainWindow", "15:50"))
        item = self.tableWidget.item(1, 11)
        item.setText(_translate("MainWindow", "16:50"))
        item = self.tableWidget.item(1, 12)
        item.setText(_translate("MainWindow", "17:50"))
        item = self.tableWidget.item(1, 13)
        item.setText(_translate("MainWindow", "18:50"))
        item = self.tableWidget.item(1, 14)
        item.setText(_translate("MainWindow", "19:00"))
        item = self.tableWidget.item(1, 15)
        item.setText(_translate("MainWindow", "19:50"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Lab"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "START"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "08:00"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "08:46"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "10:00"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("MainWindow", "10:46"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("MainWindow", "11:31"))
        item = self.tableWidget.item(2, 7)
        item.setText(_translate("MainWindow", "12:16"))
        item = self.tableWidget.item(2, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(2, 9)
        item.setText(_translate("MainWindow", "14:00"))
        item = self.tableWidget.item(2, 10)
        item.setText(_translate("MainWindow", "14:46"))
        item = self.tableWidget.item(2, 11)
        item.setText(_translate("MainWindow", "16:00"))
        item = self.tableWidget.item(2, 12)
        item.setText(_translate("MainWindow", "16:46"))
        item = self.tableWidget.item(2, 13)
        item.setText(_translate("MainWindow", "17:31"))
        item = self.tableWidget.item(2, 14)
        item.setText(_translate("MainWindow", "18:16"))
        item = self.tableWidget.item(2, 15)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "END"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "08:45"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "09:30"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "10:45"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("MainWindow", "11:30"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("MainWindow", "12:15"))
        item = self.tableWidget.item(3, 7)
        item.setText(_translate("MainWindow", "13:00"))
        item = self.tableWidget.item(3, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(3, 9)
        item.setText(_translate("MainWindow", "14:45"))
        item = self.tableWidget.item(3, 10)
        item.setText(_translate("MainWindow", "15:30"))
        item = self.tableWidget.item(3, 11)
        item.setText(_translate("MainWindow", "16:45"))
        item = self.tableWidget.item(3, 12)
        item.setText(_translate("MainWindow", "17:30"))
        item = self.tableWidget.item(3, 13)
        item.setText(_translate("MainWindow", "18:15"))
        item = self.tableWidget.item(3, 14)
        item.setText(_translate("MainWindow", "19:00"))
        item = self.tableWidget.item(3, 15)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Monday"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "Theory"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "A1"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "F1"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "D1"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("MainWindow", "TB1"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("MainWindow", "TG1"))
        item = self.tableWidget.item(4, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(4, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(4, 9)
        item.setText(_translate("MainWindow", "A2"))
        item = self.tableWidget.item(4, 10)
        item.setText(_translate("MainWindow", "F2"))
        item = self.tableWidget.item(4, 11)
        item.setText(_translate("MainWindow", "D2"))
        item = self.tableWidget.item(4, 12)
        item.setText(_translate("MainWindow", "TB2"))
        item = self.tableWidget.item(4, 13)
        item.setText(_translate("MainWindow", "TG2"))
        item = self.tableWidget.item(4, 14)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(4, 15)
        item.setText(_translate("MainWindow", "V3"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "Lab"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "L1"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "L2"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("MainWindow", "L3"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("MainWindow", "L4"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("MainWindow", "L5"))
        item = self.tableWidget.item(5, 7)
        item.setText(_translate("MainWindow", "L6"))
        item = self.tableWidget.item(5, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(5, 9)
        item.setText(_translate("MainWindow", "L31"))
        item = self.tableWidget.item(5, 10)
        item.setText(_translate("MainWindow", "L32"))
        item = self.tableWidget.item(5, 11)
        item.setText(_translate("MainWindow", "L33"))
        item = self.tableWidget.item(5, 12)
        item.setText(_translate("MainWindow", "L34"))
        item = self.tableWidget.item(5, 13)
        item.setText(_translate("MainWindow", "L35"))
        item = self.tableWidget.item(5, 14)
        item.setText(_translate("MainWindow", "L36"))
        item = self.tableWidget.item(5, 15)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "Tuesday"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "Theory"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "B1"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("MainWindow", "G1"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("MainWindow", "E1"))
        item = self.tableWidget.item(6, 5)
        item.setText(_translate("MainWindow", "TC1"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("MainWindow", "TAA1"))
        item = self.tableWidget.item(6, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(6, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(6, 9)
        item.setText(_translate("MainWindow", "B2"))
        item = self.tableWidget.item(6, 10)
        item.setText(_translate("MainWindow", "G2"))
        item = self.tableWidget.item(6, 11)
        item.setText(_translate("MainWindow", "E2"))
        item = self.tableWidget.item(6, 12)
        item.setText(_translate("MainWindow", "TC2"))
        item = self.tableWidget.item(6, 13)
        item.setText(_translate("MainWindow", "TAA2"))
        item = self.tableWidget.item(6, 14)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(6, 15)
        item.setText(_translate("MainWindow", "V4"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "Lab"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "L7"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("MainWindow", "L8"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("MainWindow", "L9"))
        item = self.tableWidget.item(7, 5)
        item.setText(_translate("MainWindow", "L10"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("MainWindow", "L11"))
        item = self.tableWidget.item(7, 7)
        item.setText(_translate("MainWindow", "L12"))
        item = self.tableWidget.item(7, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(7, 9)
        item.setText(_translate("MainWindow", "L37"))
        item = self.tableWidget.item(7, 10)
        item.setText(_translate("MainWindow", "L38"))
        item = self.tableWidget.item(7, 11)
        item.setText(_translate("MainWindow", "L39"))
        item = self.tableWidget.item(7, 12)
        item.setText(_translate("MainWindow", "L40"))
        item = self.tableWidget.item(7, 13)
        item.setText(_translate("MainWindow", "L41"))
        item = self.tableWidget.item(7, 14)
        item.setText(_translate("MainWindow", "L42"))
        item = self.tableWidget.item(7, 15)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "Wednesday"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "Theory"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("MainWindow", "C1"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("MainWindow", "A1"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("MainWindow", "F1"))
        item = self.tableWidget.item(8, 5)
        item.setText(_translate("MainWindow", "V1"))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("MainWindow", "V2"))
        item = self.tableWidget.item(8, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(8, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(8, 9)
        item.setText(_translate("MainWindow", "C2"))
        item = self.tableWidget.item(8, 10)
        item.setText(_translate("MainWindow", "A2"))
        item = self.tableWidget.item(8, 11)
        item.setText(_translate("MainWindow", "F2"))
        item = self.tableWidget.item(8, 12)
        item.setText(_translate("MainWindow", "TD2"))
        item = self.tableWidget.item(8, 13)
        item.setText(_translate("MainWindow", "TBB2"))
        item = self.tableWidget.item(8, 14)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(8, 15)
        item.setText(_translate("MainWindow", "V5"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "Lab"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("MainWindow", "L13"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("MainWindow", "L14"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("MainWindow", "L15"))
        item = self.tableWidget.item(9, 5)
        item.setText(_translate("MainWindow", "L16"))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(9, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(9, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(9, 9)
        item.setText(_translate("MainWindow", "L43"))
        item = self.tableWidget.item(9, 10)
        item.setText(_translate("MainWindow", "L44"))
        item = self.tableWidget.item(9, 11)
        item.setText(_translate("MainWindow", "L45"))
        item = self.tableWidget.item(9, 12)
        item.setText(_translate("MainWindow", "L46"))
        item = self.tableWidget.item(9, 13)
        item.setText(_translate("MainWindow", "L47"))
        item = self.tableWidget.item(9, 14)
        item.setText(_translate("MainWindow", "L48"))
        item = self.tableWidget.item(9, 15)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "Thursday"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("MainWindow", "Theory"))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("MainWindow", "D1"))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("MainWindow", "B1"))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("MainWindow", "G1"))
        item = self.tableWidget.item(10, 5)
        item.setText(_translate("MainWindow", "TE1"))
        item = self.tableWidget.item(10, 6)
        item.setText(_translate("MainWindow", "TCC1"))
        item = self.tableWidget.item(10, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(10, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(10, 9)
        item.setText(_translate("MainWindow", "D2"))
        item = self.tableWidget.item(10, 10)
        item.setText(_translate("MainWindow", "B2"))
        item = self.tableWidget.item(10, 11)
        item.setText(_translate("MainWindow", "G2"))
        item = self.tableWidget.item(10, 12)
        item.setText(_translate("MainWindow", "TE2"))
        item = self.tableWidget.item(10, 13)
        item.setText(_translate("MainWindow", "TCC2"))
        item = self.tableWidget.item(10, 14)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(10, 15)
        item.setText(_translate("MainWindow", "V6"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("MainWindow", "Lab"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("MainWindow", "L19"))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("MainWindow", "L20"))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("MainWindow", "L21"))
        item = self.tableWidget.item(11, 5)
        item.setText(_translate("MainWindow", "L22"))
        item = self.tableWidget.item(11, 6)
        item.setText(_translate("MainWindow", "L23"))
        item = self.tableWidget.item(11, 7)
        item.setText(_translate("MainWindow", "L24"))
        item = self.tableWidget.item(11, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(11, 9)
        item.setText(_translate("MainWindow", "L49"))
        item = self.tableWidget.item(11, 10)
        item.setText(_translate("MainWindow", "L50"))
        item = self.tableWidget.item(11, 11)
        item.setText(_translate("MainWindow", "L51"))
        item = self.tableWidget.item(11, 12)
        item.setText(_translate("MainWindow", "L52"))
        item = self.tableWidget.item(11, 13)
        item.setText(_translate("MainWindow", "L53"))
        item = self.tableWidget.item(11, 14)
        item.setText(_translate("MainWindow", "L54"))
        item = self.tableWidget.item(11, 15)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "Friday"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("MainWindow", "Theory"))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("MainWindow", "E1"))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("MainWindow", "C1"))
        item = self.tableWidget.item(12, 4)
        item.setText(_translate("MainWindow", "TA1"))
        item = self.tableWidget.item(12, 5)
        item.setText(_translate("MainWindow", "TF1"))
        item = self.tableWidget.item(12, 6)
        item.setText(_translate("MainWindow", "TD1"))
        item = self.tableWidget.item(12, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(12, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(12, 9)
        item.setText(_translate("MainWindow", "E2"))
        item = self.tableWidget.item(12, 10)
        item.setText(_translate("MainWindow", "C2"))
        item = self.tableWidget.item(12, 11)
        item.setText(_translate("MainWindow", "TA2"))
        item = self.tableWidget.item(12, 12)
        item.setText(_translate("MainWindow", "TF2"))
        item = self.tableWidget.item(12, 13)
        item.setText(_translate("MainWindow", "TDD2"))
        item = self.tableWidget.item(12, 14)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(12, 15)
        item.setText(_translate("MainWindow", "V7"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("MainWindow", "Lab"))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("MainWindow", "L25"))
        item = self.tableWidget.item(13, 3)
        item.setText(_translate("MainWindow", "L26"))
        item = self.tableWidget.item(13, 4)
        item.setText(_translate("MainWindow", "L27"))
        item = self.tableWidget.item(13, 5)
        item.setText(_translate("MainWindow", "L28"))
        item = self.tableWidget.item(13, 6)
        item.setText(_translate("MainWindow", "L29"))
        item = self.tableWidget.item(13, 7)
        item.setText(_translate("MainWindow", "L30"))
        item = self.tableWidget.item(13, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(13, 9)
        item.setText(_translate("MainWindow", "L55"))
        item = self.tableWidget.item(13, 10)
        item.setText(_translate("MainWindow", "L56"))
        item = self.tableWidget.item(13, 11)
        item.setText(_translate("MainWindow", "L57"))
        item = self.tableWidget.item(13, 12)
        item.setText(_translate("MainWindow", "L58"))
        item = self.tableWidget.item(13, 13)
        item.setText(_translate("MainWindow", "L59"))
        item = self.tableWidget.item(13, 14)
        item.setText(_translate("MainWindow", "L60"))
        item = self.tableWidget.item(13, 15)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("MainWindow", "Saturday"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("MainWindow", "Theory"))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("MainWindow", "V8"))
        item = self.tableWidget.item(14, 3)
        item.setText(_translate("MainWindow", "X11"))
        item = self.tableWidget.item(14, 4)
        item.setText(_translate("MainWindow", "X12"))
        item = self.tableWidget.item(14, 5)
        item.setText(_translate("MainWindow", "Y11"))
        item = self.tableWidget.item(14, 6)
        item.setText(_translate("MainWindow", "Y12"))
        item = self.tableWidget.item(14, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(14, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(14, 9)
        item.setText(_translate("MainWindow", "X21"))
        item = self.tableWidget.item(14, 10)
        item.setText(_translate("MainWindow", "Z21"))
        item = self.tableWidget.item(14, 11)
        item.setText(_translate("MainWindow", "Y21"))
        item = self.tableWidget.item(14, 12)
        item.setText(_translate("MainWindow", "W21"))
        item = self.tableWidget.item(14, 13)
        item.setText(_translate("MainWindow", "W22"))
        item = self.tableWidget.item(14, 14)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(14, 15)
        item.setText(_translate("MainWindow", "V9"))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("MainWindow", "Lab"))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("MainWindow", "L71"))
        item = self.tableWidget.item(15, 3)
        item.setText(_translate("MainWindow", "L72"))
        item = self.tableWidget.item(15, 4)
        item.setText(_translate("MainWindow", "L73"))
        item = self.tableWidget.item(15, 5)
        item.setText(_translate("MainWindow", "L74"))
        item = self.tableWidget.item(15, 6)
        item.setText(_translate("MainWindow", "L75"))
        item = self.tableWidget.item(15, 7)
        item.setText(_translate("MainWindow", "L76"))
        item = self.tableWidget.item(15, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(15, 9)
        item.setText(_translate("MainWindow", "L77"))
        item = self.tableWidget.item(15, 10)
        item.setText(_translate("MainWindow", "L78"))
        item = self.tableWidget.item(15, 11)
        item.setText(_translate("MainWindow", "L79"))
        item = self.tableWidget.item(15, 12)
        item.setText(_translate("MainWindow", "L80"))
        item = self.tableWidget.item(15, 13)
        item.setText(_translate("MainWindow", "L81"))
        item = self.tableWidget.item(15, 14)
        item.setText(_translate("MainWindow", "L82"))
        item = self.tableWidget.item(15, 15)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("MainWindow", "Sunday"))
        item = self.tableWidget.item(16, 1)
        item.setText(_translate("MainWindow", "Theory"))
        item = self.tableWidget.item(16, 2)
        item.setText(_translate("MainWindow", "V10"))
        item = self.tableWidget.item(16, 3)
        item.setText(_translate("MainWindow", "Y11"))
        item = self.tableWidget.item(16, 4)
        item.setText(_translate("MainWindow", "Y12"))
        item = self.tableWidget.item(16, 5)
        item.setText(_translate("MainWindow", "X11"))
        item = self.tableWidget.item(16, 6)
        item.setText(_translate("MainWindow", "X12"))
        item = self.tableWidget.item(16, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(16, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(16, 9)
        item.setText(_translate("MainWindow", "Y21"))
        item = self.tableWidget.item(16, 10)
        item.setText(_translate("MainWindow", "Z21"))
        item = self.tableWidget.item(16, 11)
        item.setText(_translate("MainWindow", "X21"))
        item = self.tableWidget.item(16, 12)
        item.setText(_translate("MainWindow", "W21"))
        item = self.tableWidget.item(16, 13)
        item.setText(_translate("MainWindow", "W22"))
        item = self.tableWidget.item(16, 14)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(16, 15)
        item.setText(_translate("MainWindow", "V11"))
        item = self.tableWidget.item(17, 1)
        item.setText(_translate("MainWindow", "Lab"))
        item = self.tableWidget.item(17, 2)
        item.setText(_translate("MainWindow", "L83"))
        item = self.tableWidget.item(17, 3)
        item.setText(_translate("MainWindow", "L84"))
        item = self.tableWidget.item(17, 4)
        item.setText(_translate("MainWindow", "L85"))
        item = self.tableWidget.item(17, 5)
        item.setText(_translate("MainWindow", "L86"))
        item = self.tableWidget.item(17, 6)
        item.setText(_translate("MainWindow", "L87"))
        item = self.tableWidget.item(17, 7)
        item.setText(_translate("MainWindow", "L88"))
        item = self.tableWidget.item(17, 8)
        item.setText(_translate("MainWindow", "LUNCH"))
        item = self.tableWidget.item(17, 9)
        item.setText(_translate("MainWindow", "L89"))
        item = self.tableWidget.item(17, 10)
        item.setText(_translate("MainWindow", "L90"))
        item = self.tableWidget.item(17, 11)
        item.setText(_translate("MainWindow", "L91"))
        item = self.tableWidget.item(17, 12)
        item.setText(_translate("MainWindow", "L92"))
        item = self.tableWidget.item(17, 13)
        item.setText(_translate("MainWindow", "L93"))
        item = self.tableWidget.item(17, 14)
        item.setText(_translate("MainWindow", "L94"))
        item = self.tableWidget.item(17, 15)
        item.setText(_translate("MainWindow", "-"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "GENERATE"))
        self.closeButton.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

